- hosts: all
  become: true
  vars_files:
    - secrets.yml
  tasks:
    - name: Update package cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade all packages
      apt:
        upgrade: yes
        autoremove: yes
        autoclean: yes

    - name: Shut down the server
      shell: shutdown now
